name: Build

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-20.04

    env:
      REPO: ghcr.io/devplayer0/kubelan

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: vars
        name: Generate build vars
        run: |
          SHA="${{ github.sha }}"
          echo "::set-output name=tag::"${SHA:0:8}-$(date +%s)Z""

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REPO }}:${{ steps.vars.outputs.tag }},${{ env.REPO }}:latest
          push: true
          cache-from: type=registry,src=${{ env.REPO }}:latest
          cache-to: type=registry,type=inline
